apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: jupyterhub
  name: jupyterhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jupyterhub
  template:
    metadata:
      labels:
        run: jupyterhub
    spec:
      containers:
      - image: jupyterhub:base
        ports:
        - containerPort: 8000
        name: jupyterhub
        volumeMounts:
        - name: config-vol
          mountPath: /jupyterhub
      volumes:
      - name: config-vol
        hostPath:
          path: /home/h/jupyter-on-k8s/docker/jupyterhub 
          type: Directory
